# Generated by Django 5.2.13 on 2026-04-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatMessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
