# Generated by Django 6.0.3 on 2026-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_posts'),
        ),
    ]
